name: "FINOS CCC Validator"
description: "A GitHub action to validate the content the services listed under the FINOS Common Cloud Controls (CCC) project."
author: "Stevie Shiells"

branding:
  icon: "check-square"
  color: "blue"

inputs:
  targetDir:
    description: "File directory path the root for the services directory"
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '--targetDir'
  - ${{ inputs.targetDir }}
